#! /bin/sh


set -x

# Fail if anything fails.
# This way, we don't have to constantly check exit statuses.
set -e


echo "=== Verify Usage Messages ==="

for p in add-vector count flip math modes repeat
do
  node examples/$p.js --help
done

echo "=== Add Vector ==="
test `node examples/add-vector.js --a=1,2,3 --b=10,10,10` = '11,12,13'

echo "=== Count ==="
node examples/count.js --count=5 --step=2 > examples/tmp-a
echo '0
2
4
6
8' > examples/tmp-b
diff -q examples/tmp-a examples/tmp-b
rm examples/tmp-a examples/tmp-b


echo "=== Flip ==="
test `node examples/flip.js -p 0` = TAILS
test `node examples/flip.js -p 1` = HEAD
